from __future__ import annotations
from .models import KnowledgeReference, ReferenceKind, Remediation, SecurityKnowledge

CWE_BASE='https://cwe.mitre.org/data/definitions/'
OWASP_BASE='https://owasp.org/Top10/'

def _refs(cwe: str, owasp: str) -> tuple[KnowledgeReference, ...]:
    number=cwe.split('-')[-1]
    return (
        KnowledgeReference(cwe, f'{CWE_BASE}{number}.html', ReferenceKind.CWE),
        KnowledgeReference(f'OWASP {owasp}', f'{OWASP_BASE}{owasp.replace(":", "_")}/', ReferenceKind.OWASP),
    )

def _k(rule_id,title,description,cwe,owasp,mitre,score,vector,summary,steps,safe,unsafe,tags):
    return SecurityKnowledge(rule_id,title,description,(cwe,),(owasp,),tuple(mitre),score,vector,
        Remediation(summary,tuple(steps),safe,unsafe),_refs(cwe,owasp),tuple(tags))

CATALOG=(
_k('ATLAS-SQL-001','SQL injection','Untrusted input is incorporated into a database query.', 'CWE-89','A03:2021',('T1190',),9.8,'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H','Use parameterized queries and bind values separately.',('Replace string-built SQL with prepared statements.','Validate identifiers that cannot be parameterized.','Use least-privileged database accounts.'),'PreparedStatement ps = c.prepareStatement("SELECT * FROM users WHERE id = ?"); ps.setString(1, id);','statement.executeQuery("SELECT * FROM users WHERE id=" + id);',('injection','database')),
_k('ATLAS-CMD-001','Command injection','Untrusted input reaches an operating-system command interpreter.', 'CWE-78','A03:2021',('T1059',),9.8,'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H','Avoid shell execution and pass fixed executable arguments.',('Use a dedicated API instead of a shell.','Allowlist commands and arguments.','Do not concatenate user input into command strings.'),'new ProcessBuilder("convert", input, output).start();','Runtime.getRuntime().exec("convert " + input);',('injection','command')),
_k('ATLAS-PATH-001','Path traversal','Untrusted path components can escape an intended directory.', 'CWE-22','A01:2021',('T1083',),8.1,'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N','Resolve paths against a fixed root and verify containment.',('Normalize the candidate path.','Reject absolute paths.','Verify the normalized path starts with the allowed root.'),'Path p = root.resolve(name).normalize(); if (!p.startsWith(root)) throw new SecurityException();','Files.readAllBytes(Paths.get(base + name));',('path','filesystem')),
_k('ATLAS-SSRF-001','Server-side request forgery','Attacker-controlled URLs cause server-side network requests.', 'CWE-918','A10:2021',('T1190',),8.2,'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N','Allowlist destinations and block private or link-local networks.',('Parse and canonicalize the URL.','Allowlist schemes and hosts.','Resolve DNS and reject private, loopback, and link-local addresses.'),'URI uri = validateAllowedDestination(input); client.send(request(uri), handler);','new URL(input).openConnection();',('ssrf','network')),
_k('ATLAS-DESER-001','Insecure deserialization','Untrusted serialized data is reconstructed as executable object graphs.', 'CWE-502','A08:2021',('T1203',),9.8,'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H','Prefer simple data formats and strictly restrict allowed types.',('Avoid native object deserialization for untrusted data.','Use explicit DTOs.','Apply type allowlists and integrity protection.'),'UserDto dto = mapper.readValue(json, UserDto.class);','new ObjectInputStream(input).readObject();',('deserialization','rce')),
_k('ATLAS-REFLECT-001','Unsafe reflection','Untrusted names or objects influence reflective class or method invocation.', 'CWE-470','A03:2021',('T1059',),8.1,'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N','Map external values to a fixed allowlist of types or operations.',('Do not pass user input to Class.forName.','Use an enum-to-handler map.','Restrict reflective access.'),'Handler h = ALLOWED_HANDLERS.get(action); h.run();','Class.forName(request.getParameter("class"));',('reflection','dynamic-code')),
_k('ATLAS-XXE-001','XML external entity injection','An XML parser may resolve attacker-controlled external entities.', 'CWE-611','A05:2021',('T1190',),8.1,'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N','Disable DTDs and external entity resolution.',('Disable DOCTYPE declarations.','Disable external general and parameter entities.','Use secure processing limits.'),'factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);','DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(input);',('xml','xxe')),
_k('ATLAS-SECRET-001','Hardcoded secret','A credential or cryptographic secret is embedded in source code.', 'CWE-798','A07:2021',('T1552.001',),7.5,'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N','Load secrets from a managed secret store and rotate exposed values.',('Remove the secret from source and history.','Rotate the credential.','Use runtime secret injection with least privilege.'),'String token = secretProvider.get("service-token");','String token = "prod-secret-123";',('secret','credential')),
_k('ATLAS-CRYPTO-001','Weak cryptography','A weak or obsolete cryptographic primitive is used.', 'CWE-327','A02:2021',('T1027',),7.4,'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N','Use modern, reviewed cryptographic algorithms and safe modes.',('Replace MD5, SHA-1, DES, and ECB mode.','Use authenticated encryption such as AES-GCM.','Use a password KDF for passwords.'),'Cipher.getInstance("AES/GCM/NoPadding");','MessageDigest.getInstance("MD5");',('crypto','weak-algorithm')),
_k('ATLAS-SPRING-EL-001','Spring expression injection','Untrusted input is evaluated as a Spring Expression Language expression.', 'CWE-917','A03:2021',('T1059',),9.8,'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H','Never evaluate user-controlled expressions; use fixed mappings.',('Replace dynamic SpEL with fixed property access.','Use SimpleEvaluationContext when expression support is unavoidable.','Allowlist permitted operations.'),'String value = ALLOWED_PROPERTIES.get(key);','parser.parseExpression(input).getValue(context);',('spring','expression','injection')),
_k('ATLAS-JPA-001','JPA query injection','Untrusted data is concatenated into JPQL or native queries.', 'CWE-89','A03:2021',('T1190',),9.1,'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H','Use named parameters or the criteria API.',('Bind all values with setParameter.','Allowlist dynamic identifiers.','Avoid concatenated JPQL fragments.'),'em.createQuery("from User u where u.name = :name").setParameter("name", name);','em.createQuery("from User u where u.name = \'" + name + "\'");',('jpa','database','injection')),
_k('ATLAS-JACKSON-001','Unsafe polymorphic deserialization','Broad polymorphic type handling can instantiate attacker-selected classes.', 'CWE-502','A08:2021',('T1203',),9.8,'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H','Avoid broad default typing and allowlist concrete subtypes.',('Disable deprecated default typing.','Use explicit DTO types.','Use a restrictive PolymorphicTypeValidator.'),'mapper.readValue(json, UserDto.class);','mapper.enableDefaultTyping();',('jackson','deserialization')),
)
